### ISSUE TITLE
static approach makes it hard to extend functionality

### ISSUE THREAD

**Issue by splitbrain** [aziraphale/email-address-validator#2]
We're currently using a patched version of the old Google Code version which has an option to allow local addresses (see 02700828f76adcfc63a9dafe75ffa941cdb9831b).

It would be possible to implement this in your version by passing a second parameter to `checkEmailAddress()` and `checkDomainPotion()` but I wonder if making this static was such a good idea...

**Comment by aziraphale** [comment]
Static classes like this is just a personal preference of mine when the class is relatively simple and is essentially just a load of methods grouped together like this. Having to create a new object every time you want to call a single validation method seems like a complete waste of time, especially in the probably-quite-small projects that I think I was using this in.

I'm surprised I didn't use `static::` calls instead of `self::`, which I think should make extending it a fair bit easier - maybe I was trying to retain compatibility with versions of PHP that didn't support the `static::` operator, I really don't recall!

Thanks for your contributions, though :)
